CREATE TABLE user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  userId NVARCHAR(32) NOT NULL COMMENT '用户标识',
  username NVARCHAR(56) NOT NULL COMMENT '用户名',
  enable BIT DEFAULT 0 COMMENT '是否启用，默认是不启用',
  createDate DATETIME COMMENT '注册日期'
);

CREATE TABLE train_ticket (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  ticketNum INT COMMENT '剩余火车票数'
);

CREATE TABLE order (
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  orderId NVARCHAR(32) UNIQUE NOT NULL COMMENT '订单ID',
  userId NVARCHAR(32) NOT NULL COMMENT '用户标识',
  ticket NVARCHAR(128) NOT NULL COMMENT '火车票信息'
);
